env_files:
  github_token: ~/.config/goreleaser/github_token

builds:
  - id: substreams-mongodb-sink
  goos:
    - linux
    - darwin
  goarch:
    - linux_amd64
    - darwin_amd64
    - darwin_arm64
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  main: ./cmd/substreams-mongodb-sink
  env:
    - CGO_ENABLED=0

archives:
  - id: substreams-mongodb-sink
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    builds:
    - substreams-mongodb-sink
    replacements:
      amd64: x86_64
      darwin: macOS
      linux: linux
    format: tar.gz
    files:
    - LICENSE
    - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpath .Version }}-next"

changelog:
  sort: asc

signs:
- cmd: keybase
  args:
    - sign
    - --infile
    - $artifact
    - --binary
    - --outfile
    - $signature
    - --detached
  signature: ${artifact}.sig
  artifacts: checksum

brews:
  - name: substreams-mongodb-sink
    ids:
      - substreams-mongodb-sink
    tap:
      owner: streamingfast
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@streamingfast.io
    homepage: "https://github.com/streamingfast/substreams-mongodb-sink"
    description: "StreamingFast mongodb load CLI"
    license: "Apache-2.0"
